{
 "title": "TempCondition",
 "description": "testing- India",
 "time": { "from": "2020-02-22T23:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Regione",
    "label": "Region",
    "query": "select distinct denominazione_regione from covid19.province"
   }
  ]
 },
 "panels": [
  {
   "title": "National trend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 18 hour) AS \"time\",\n  sum(totale_casi)\nFROM covid19.province\ngroup by data\nORDER BY data"
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 22, "w": 10, "x": 14, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT \n  longitude, latitude, denominazione_provincia, max(totale_casi) as tot\nFROM covid19.province\nwhere longitude<>0\n  and  $__timeFilter(data)\ngroup by longitude, latitude, denominazione_provincia\norder by longitude, latitude, denominazione_provincia"
    }
   ]
  },
  {
   "title": "National trend COPY For Testing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 18 hour) AS \"time\",\n  sum(totale_casi)\nFROM covid19.province\ngroup by data\nORDER BY data"
    }
   ]
  },
  {
   "title": "Differential (new infections)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select date_add(time1, interval 1 day) as \"time\", sum2-sum1 Delta\n  from (SELECT data AS \"time1\", sum(totale_casi) AS sum1 FROM covid19.province group by data) a,\n       (SELECT date_sub(data, interval 1 day) AS \"time2\", sum(totale_casi) AS sum2 FROM covid19.province group by data) b\n where time1=time2\n union \n select STR_TO_DATE('2020-02-24', '%Y-%m-%d'), 0\n  order by 1"
    }
   ]
  },
  {
   "title": "Datasource: https://github.com/pcm-dpc/COVID-19",
   "type": "text",
   "gridPos": { "h": 1, "w": 10, "x": 14, "y": 22 },
   "options": {
    "content": "<a href=\"https://github.com/meob/my2Collector\">Github</a>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  c1 AS \"time\",\n  v1\nFROM mylog\nWHERE\n  $__timeFilter(c1)\nORDER BY c1"
    }
   ]
  },
  {
   "title": "Infected by Region",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 18 hour) AS \"time\",\n  denominazione_regione AS metric,\n  sum(totale_casi)\nFROM covid19.province\ngroup by denominazione_regione, data\nORDER BY data, denominazione_regione"
    }
   ]
  },
  {
   "title": "Infected by Province (choosen Region)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 18 hour) AS \"time\",\n  denominazione_provincia AS metric,\n  sum(totale_casi)\nFROM covid19.province\nwhere denominazione_regione='$Regione'\ngroup by denominazione_provincia, data\nORDER BY data, denominazione_provincia"
    }
   ]
  }
 ]
}